#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Illegal number of parameters"
    echo "Ex Usage: ./rebuild ~/working"
    exit 2
fi

DIR=$1
mkdir -p ${DIR}/recipes/
mkdir -p ${DIR}/index/

rm -f ${DIR}/recipes/*
rm -f ${DIR}/index/*
rm -f ${DIR}/container.pool
rm -f ${DIR}/destor.stat
rm -f ${DIR}/manifest
